[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "d6lease"
version = "0.1"
authors = [
  { name="Drew Gochenaur" }
]
requires-python = ">=3.8"
dependencies = [
  "textx"
]

[options]
include_package_data = true
